# generated by fastapi-codegen:
#   filename:  path_parameter_schema_reference.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title='path_parameter_schema_reference',
    version='1.0.0',
)


@app.get('/widgets/{widget}', response_model=None)
def get_widget(widget: str) -> None:
    pass
