# generated by fastapi-codegen:
#   filename:  path_parameter_schema_reference.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class WidgetPath(BaseModel):
    id: str
