# generated by fastapi-codegen:
#   filename:  recursion.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI
from pydantic import constr

app = FastAPI(
    title='REST API',
    version='0.0.1',
    servers=[{'url': 'https://api.something.com/1'}],
)


@app.get('/actions/{id}', response_model=None)
def get_actions_id(id: constr(regex=r'^[0-9a-fA-F]{24}$')) -> None:
    pass
