# generated by fastapi-codegen:
#   filename:  recursion.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class ID(BaseModel):
    __root__: constr(regex=r'^[0-9a-fA-F]{24}$') = Field(
        ..., example='5abbe4b7ddc1b351ef961414'
    )


class Card(BaseModel):
    id: Optional[ID] = None


class Board(BaseModel):
    id: Optional[ID] = None


class Data(BaseModel):
    card: Optional[Card] = None
    board: Optional[Board] = None


class Action(BaseModel):
    data: Optional[Data] = None
