# generated by fastapi-codegen:
#   filename:  recursion.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, constr


class Card(BaseModel):
    id: Optional[constr(regex=r'^[0-9a-fA-F]{24}$')] = None


class Board(BaseModel):
    id: Optional[constr(regex=r'^[0-9a-fA-F]{24}$')] = None


class Data(BaseModel):
    card: Optional[Card] = None
    board: Optional[Board] = None


class Action(BaseModel):
    data: Optional[Data] = None
