# generated by fastapi-codegen:
#   filename:  discriminated_union_simple_type.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title='discriminated_union_simple_type',
    version='1.0.0',
)
