# generated by fastapi-codegen:
#   filename:  discriminated_union_simple_type.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, Field, RootModel


class ImageUrl(BaseModel):
    kind: str
    image_url: str


class AudioUrl(BaseModel):
    kind: str
    audio_url: str


class DocumentUrl(BaseModel):
    kind: str
    document_url: str


class BinaryContent(BaseModel):
    kind: str
    binary_content: str


class Content(RootModel[Union[str, ImageUrl, AudioUrl, DocumentUrl, BinaryContent]]):
    root: Union[str, ImageUrl, AudioUrl, DocumentUrl, BinaryContent] = Field(
        ..., description='Union type representing different content formats'
    )
