# generated by fastapi-codegen:
#   filename:  upload.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Error(BaseModel):
    code: int
    message: str
