repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: "^fastapi_code_generator|^tests"
        exclude: "^tests/data"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "^fastapi_code_generator|^tests"
        exclude: "^tests/data"
