repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        files: "^fastapi_code_generator|^tests"
        exclude: "^tests/data"
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        files: "^fastapi_code_generator|^tests"
        exclude: "^tests/data"
