[project]
site_name = "fastapi-code-generator"
site_description = "This code generator creates FastAPI apps from OpenAPI files."
site_url = "https://fastapi-code-generator.koxudaxi.dev"
repo_name = "koxudaxi/fastapi-code-generator"
repo_url = "https://github.com/koxudaxi/fastapi-code-generator"

nav = [
  { "Overview" = "index.md" },
  { "CLI Reference" = "cli-reference.md" },
  { "Supported Formats" = "supported_formats.md" },
  { "Development & Contributing" = "development-contributing.md" }
]

[project.theme]
features = [
  "content.code.copy",
  "navigation.instant",
  "navigation.tracking",
  "navigation.sections",
  "search.highlight",
  "search.share",
  "toc.follow"
]

[[project.theme.palette]]
scheme = "default"
primary = "light blue"
accent = "light blue"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "light blue"
accent = "light blue"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

[project.plugins.search]
