# generated by datamodel-codegen:
#   filename:  fastapi_code_generator/config.py

from __future__ import annotations

from typing import Literal, Optional, TypedDict

from typing_extensions import NotRequired


class GenerateConfigDict(TypedDict):
    custom_visitors: NotRequired[Optional[list[str]]]
    disable_timestamp: NotRequired[bool]
    encoding: NotRequired[str]
    enum_field_as_literal: NotRequired[Optional[Literal['all', 'one']]]
    generate_routers: NotRequired[bool]
    input_file: str
    model_file: NotRequired[Optional[str]]
    model_template_dir: NotRequired[Optional[str]]
    output_dir: str
    output_model_type: NotRequired[
        Literal[
            'pydantic.BaseModel',
            'pydantic_v2.BaseModel',
            'dataclasses.dataclass',
            'typing.TypedDict',
            'msgspec.Struct',
        ]
    ]
    python_version: NotRequired[Literal['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']]
    specify_tags: NotRequired[Optional[str]]
    template_dir: NotRequired[Optional[str]]
