# generated by fastapi-codegen:
#   filename:  duplicate_request_param.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Request

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    description='API definition for duplicate request parameters',
)


@app.post('/pets/{id}/image/octet-stream', response_model=None, tags=['pets'])
def upload_pet_image_with_duplicate_request(
    id: str, request: Optional[str] = None
) -> None:
    """
    Upload image with octet-stream and request query
    """
    pass
