# generated by fastapi-codegen:
#   filename:  modular_reference.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI, Path

from .models.pets import Pet

app = FastAPI(
    version='1.0.0',
    title='modular_reference_template',
    license={'name': 'MIT'},
    servers=[{'url': 'http://petstore.swagger.io/v1'}],
)


@app.get('/pets/{petId}', response_model=Pet, tags=['pets'])
def show_pet_by_id(pet_id: str = Path(..., alias='petId')) -> Pet:
    """
    Info for a specific pet
    """
    pass
