# generated by fastapi-codegen:
#   filename:  responses_without_schema.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    version='1.0.0',
    title='Response Coverage API',
)


@app.get('/empty200', response_model=None, tags=['coverage'])
def get_empty200() -> None:
    pass


@app.get('/string-with-empty-404', response_model=str, tags=['coverage'])
def get_string_with_empty404() -> str:
    pass
