# generated by fastapi-codegen:
#   filename:  duplicate_param.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI
from pydantic import constr

app = FastAPI(
    title='REST API',
    version='0.0.1',
    servers=[{'url': 'https://api.something.com/1'}],
)


@app.delete('/boards/{id}', response_model=None)
def delete_boards_id(id: Union[str, constr(regex=r'^[0-9a-fA-F]{24}$')]) -> None:
    """
    Delete a Board
    """
    pass
