# generated by fastapi-codegen:
#   filename:  duplicate_param.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ID(BaseModel):
    __root__: constr(regex=r'^[0-9a-fA-F]{24}$') = Field(
        ..., example='5abbe4b7ddc1b351ef961414'
    )
