# generated by fastapi-codegen:
#   filename:  content_in_parameters.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Query

from .models import Pet

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    description='This description is for testing\nmulti-line\ndescription\n',
    servers=[{'url': 'http://petstore.swagger.io/v1'}],
)


@app.get('/{supi_or_suci}/security-information-rg', response_model=None)
def get_rg_auth_data(plmn_id: Optional[Pet] = Query(None, alias='plmn-id')) -> None:
    """
    Get authentication data for the FN-RG
    """
    pass
