# generated by fastapi-codegen:
#   filename:  duplicate_anonymus_parameter.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI

from .models import HTTPValidationError

app = FastAPI(
    title='test',
    version='0.1.0',
    servers=[
        {'url': 'http://locahost:8000', 'description': 'Local development server'}
    ],
)


@app.get(
    '/get-sheet', response_model=str, responses={'422': {'model': HTTPValidationError}}
)
def get_sheet_get_sheet_get(
    spreadsheet_id: Optional[str] = None,
) -> Union[str, HTTPValidationError]:
    """
    Get Sheet
    """
    pass


@app.post(
    '/update-sheet',
    response_model=str,
    responses={'422': {'model': HTTPValidationError}},
)
def update_sheet_update_sheet_post(
    spreadsheet_id: Optional[str] = None,
) -> Union[str, HTTPValidationError]:
    """
    Update Sheet
    """
    pass
