# generated by fastapi-codegen:
#   filename:  reuse_model.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import SourceGetResponse, TargetGetResponse

app = FastAPI(
    version='1.0.0',
    title='Reuse model',
)


@app.get('/source', response_model=SourceGetResponse)
def get_source() -> SourceGetResponse:
    pass


@app.get('/target', response_model=TargetGetResponse)
def get_target() -> TargetGetResponse:
    pass
