# generated by fastapi-codegen:
#   filename:  simple.yaml

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI, Path

from .models import Error, Pets

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    description='This description is for testing\nmulti-line\ndescription\n',
    servers=[{'url': 'http://petstore.swagger.io/v1'}],
)


@app.get(
    '/pets', response_model=Pets, responses={'default': {'model': Error}}, tags=['pets']
)
def list_pets(limit: Optional[int] = None) -> Union[Pets, Error]:
    """
    List all pets
    """
    pass


@app.post(
    '/pets', response_model=None, responses={'default': {'model': Error}}, tags=['pets']
)
def create_pets() -> Optional[Error]:
    """
    Create a pet
    """
    pass


@app.get(
    '/pets/{petId}',
    response_model=Pets,
    responses={'default': {'model': Error}},
    tags=['pets'],
)
def show_pet_by_id(pet_id: str = Path(..., alias='petId')) -> Union[Pets, Error]:
    """
    Info for a specific pet
    """
    pass
