# generated by fastapi-codegen:
#   filename:  body_and_parameters.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import List, Optional

from fastapi import FastAPI, Query

from .models import Pet, PetForm, Pets

app = FastAPI()


@app.get('/pets', response_model=List[Pet])
def list_pets(
    limit: Optional[int] = 0,
    home_address: Optional[str] = Query('Unknown', alias='HomeAddress'),
    kind: Optional[str] = 'dog',
) -> List[Pet]:
    pass


@app.post('/pets', response_model=None)
def post_pets(body: PetForm) -> None:
    pass


@app.get('/pets/{pet_id}', response_model=Pets)
def show_pet_by_id(pet_id: str = Query(..., alias='petId')) -> Pets:
    pass


@app.put('/pets/{pet_id}', response_model=None)
def put_pets__pet_id_(
    pet_id: str = Query(..., alias='petId'), body: PetForm = None
) -> None:
    pass
