# generated by fastapi-codegen:
#   filename:  reuse_model.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class SourceGetResponse(BaseModel):
    id: int
    name: str


class TargetGetResponse(BaseModel):
    id: int
    name: str
