# generated by fastapi-codegen:
#   filename:  discriminator_in_root_with_properties.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title='discriminator_in_root_with_properties',
    version='1.0.0',
    servers=[{'url': 'https://your-domain.atlassian.net'}],
)
