# generated by fastapi-codegen:
#   filename:  query_array_parameter.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Query

from .models import Error, Pet

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    servers=[{'url': 'http://petstore.swagger.io/v1'}],
)


@app.get(
    '/pets',
    response_model=List[Pet],
    responses={'default': {'model': Error}},
    tags=['pets'],
)
def list_pets(
    limit: Optional[int] = None,
    pet_ids: Optional[List[int]] = Query(None, alias='petIds'),
) -> Union[List[Pet], Error]:
    """
    List all pets
    """
    pass
