# generated by fastapi-codegen:
#   filename:  nullable_test.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import User

app = FastAPI(
    version='1.0.0',
    title='Nullable Test API',
    description='API for testing nullable field behavior',
    servers=[{'url': 'http://api.example.com/v1'}],
)


@app.get('/users', response_model=User)
def get_user_details() -> User:
    """
    Get user details
    """
    pass
