# generated by fastapi-codegen:
#   filename:  nullable_test.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    id: int
    username: str
    email: Optional[str] = Field(
        None, description="User's email address (explicitly nullable)"
    )
    phone: str = Field(..., description="User's phone number (explicitly non-nullable)")
    nickname: Optional[str] = Field(
        None, description="User's nickname (optional, not nullable under strict mode)"
    )
