# generated by fastapi-codegen:
#   filename:  content_in_parameters_inline.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Path, Query

from .models import PlmnId

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    description='This description is for testing\nmulti-line\ndescription\n',
    servers=[{'url': 'http://petstore.swagger.io/v1'}],
)


@app.get(
    '/{supiOrSuci}/security-information-rg-inline',
    response_model=None,
    tags=['Get Auth Data for FN-RG'],
)
def get_rg_auth_data_inline(
    supi_or_suci: str = Path(..., alias='supiOrSuci'),
    plmn_id: Optional[PlmnId] = Query(None, alias='plmn-id'),
) -> None:
    """
    Get authentication data for the FN-RG inline
    """
    pass
