# generated by fastapi-codegen:
#   filename:  content_in_parameters_inline.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class PlmnId(BaseModel):
    mcc: str
    mnc: str
