# generated by fastapi-codegen:
#   filename:  oas_response_reference.yaml
#   timestamp: 2020-06-19T00:00:00+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI

from .models import Error, Pet

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    description='This description is for testing\nmulti-line\ndescription\n',
)


@app.get('/pets', response_model=List[Pet], responses={'default': {'model': Error}})
def list_pets(limit: Optional[int] = 0) -> Union[List[Pet], Error]:
    """
    List all pets
    """
    pass
