name: Docs

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
        allow-prereleases: true

    - uses: astral-sh/setup-uv@v8.0.0
      with:
        enable-cache: true
    - name: Install tox
      run: uv tool install tox --with tox-uv
    - name: build site
      run: tox -e docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
