name: Publish

on:
  push:
    tags:
      - "**"

jobs:
  build-n-publish:
    name: Build and publish Python distributions
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true
      - name: Build distributions
        run: uv build --sdist --wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
